source 'https://rubygems.org'
ruby '3.2.2'

gem 'rails', '~> 7.0.7'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.0'
gem 'importmap-rails'
gem 'turbo-rails'
gem 'stimulus-rails'
gem 'jbuilder'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'bootsnap', require: false
gem 'image_processing', '~> 1.2'
gem 'friendly_id', '~> 5.5'

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem 'web-console'
end
